name: CI
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Code checkout
        uses: actions/checkout@v4
      - name: Compile tests
        uses: gcc test/test.c -o testbin
      - name: Run tests
        uses: ./testbin
